[workspace]
resolver = "2"
members = ["app", "crates/fluid-2d"]
default-members = ["app"]

[workspace.dependencies]
bevy = { version = "0.19.1", default-features = false, features = ["2d", "ui", "bevy_feathers"] }
rand = "0.10"

[profile.dev]
opt-level = 3

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
panic = "abort"
opt-level = 3
codegen-units = 1
incremental = false
debug = false
