[package]
name = "bevy_fluid_sim"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 3

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
incremental = false
debug = false

[dependencies]
bevy = { version = "0.19.1", features = ["bevy_feathers"] }
rand = "0.10"

[features]
dev = ["bevy/dynamic_linking"]
